body:
  - type: markdown
    title: User Experience Design
    body: Wir finden die jeweils beste Lösung für jede Zielgruppe und jeden Use Case.
    addon:
      type: lottie
      path: assets/user-experience-design_small.json

  - type: markdown
    title: User Interface Design
    body: Wir gestalten ansprechende und intuitive User Interfaces.
    addon:
      type: lottie
      path: assets/user-inerface-design_small.json

  - type: markdown
    title: Web + App Development
    body: Wir entwickeln zukunftssichere Lösungen mit Hilfe modernster Technologien.
    addon:
      type: lottie
      path: assets/web-app-development_small.json

  - type: markdown
    title: Strategie + Beratung
    body: Wir konzipieren Lösungen, mit denen Sie Ihre digitalen Chancen nutzen.
    addon:
      type: lottie
      path: assets/beratung-und-strategie_small.json

  - type: markdown
    title: Online Marketing
    body: Wir sorgen dafür, dass Ihre Kommunikation auffällt und im Gedächtnis bleibt.
    addon:
      type: lottie
      path: assets/online-marketing_small.json

  - type: markdown
    title: Digital Products
    body: Wir realisieren Anwendungen, die Ihre Zielgruppe nachhaltig begeistern.
    addon:
      type: lottie
      path: assets/digitale-produkte_small.json
      

