name: comment
on: pull_request
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Thanks for your contribution to the Convoy Interactive Website. You may check your updates at: https://stage.convoyinteractive.com/?preview=$(echo ${GITHUB_REF#refs/heads/})"
