name: prettier

on: push

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        run: npm run prettier

      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply changes from prettier
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
