name: prettier

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Run prettier
        run: npm run prettier

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply changes from prettier
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
